### ISSUE TITLE
Data Gathering Team - Setup Tool and gather data

### ISSUE THREAD

**Issue by DanielMadaghjian** [DanielMadaghjian/Sustainable-Software-Project#1]
# Summary
Everyone setup the "open hardware monitoring" tool on each computer. Run the program for 10 seconds, and gather the data in the form of a dictionary for the data analysis team to use. On top of this, attempt to convert the code from c# to python. 

## Resources
- [Open Hardware Monitoring Tool](https://openhardwaremonitor.org/)
- [Open Hardware Monitoring Tool Tutorial](https://performancepsu.com/open-hardware-monitor-source-code-dll-with-c/)

## Tasks
- [x] Each person set up the "open hardware monitoring" tool, along with the code to gather data
- [x] Run the program for 10 seconds, and gather the data in the form of a dictionary
- [x] Convert c# code to python
- [x] Create feature branch. Push to this branch. Create pull request to 'data-gathering' branch.
