### ISSUE TITLE
Data Analysis Team - Test Mock Data 

### ISSUE THREAD

**Issue by DanielMadaghjian** [DanielMadaghjian/Sustainable-Software-Project#2]
# Summary
Set up program in Python, which accepts data from the Data-Gathering-Team in the form of dictionary. Create mock data to carry out analysis and calculations on the power usage of an application, which can be used by the frontend. 

## Tasks
- [x] Setup python program
- [x] Create basic mock data in the form of a dictionary
- [x] Create functions to calculate necessary results which the frontend will display
- [x] Create feature branch. Push to this branch. Create Pull request to 'data-analysis' branch.
