### ISSUE TITLE
Integrate frontend and backend

### ISSUE THREAD

**Issue by DanielMadaghjian** [DanielMadaghjian/Sustainable-Software-Project#20]
# Summary
This is the final part of our version 1 release. We want to integrate the frontend and backend, and check that it works fine.

## Tasks
- [x] Backend set up so that frontend can call a function to retrieve data
- [x] Frontend call function in the backend, once the user hits the start button
- [x] Create pull requests to the dev branch
- [x] Merge the frontend and backend branch into dev
- [x] Merge dev into main, finalizing our release
