### ISSUE TITLE
Frontend Team - Setup frontend application and research

### ISSUE THREAD

**Issue by DanielMadaghjian** [DanielMadaghjian/Sustainable-Software-Project#3]
# Summary
Decide on what python frontend framework to use, and setup a basic frontend application. Carry out research into the area of power usage, carbon emissions etc... and display this information. Brainstorm how the frontend will look, how it will interact with the user, and what the results will look like/show. 

## Tasks
- [x] Decide on what framework to use on the frontend
- [x] Setup a basic application. 
- [x] Research anything useful with regards to power usage, and the effect of software on the environment. Display this information
- [x] Create feature branch. Push to this branch. Pull request to frontend branch.
- [x] Brainstorm!!!!
